config/routes.rb
Rails.application.routes.draw do
  devise_for :employers, controllers: {
  	sessions: 'employers/sessions',
  	passwords: 'employers/passwords',
  	registrations: 'employers/registrations'
  }

  devise_for :creaters, controllers: {
  	sessions: 'creaters/sessions',
  	passwords: 'creaters/passwords',
  	registrations: 'creaters/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get '/about', to: 'homes#about'
  root 'articles#index'

  namespace :creaters do
    resources :projects, only: [:index,:show, :edit, :update, :destroy]
    resources :offers do
      resources :requests, only: [:new, :create, :edit, :update, :destroy]
    end
    get '/requests', to: 'requests#index'
  end

  resources :creaters do
    patch :creater_status
    get '/cancel', to: 'creaters#cancel'
  end

  namespace :employers do
    resources :creaters, only: [:index, :show]
    resources :offers, only: [:index, :show, :new, :create, :edit, :update] do
      resources :requests, only: [:index, :show, :edit, :update, :destroy] do
          resources :projects, only: [:new, :create, :destroy]
      end
    end
  end

  resources :employers do
    patch :employer_status
    get '/cancel', to: 'employers#cancel'
  end

end

app/models/creater.rb
class Creater < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :articles
	has_many :projects
	has_many :requests
	enum creater_status: {対応可: 0, 退会済: 1}
  validates :creater_status, inclusion: { in: Creater.creater_statuses.keys }
  validates :name, presence: true
  validates :kana_name, presence: true
  validates :career, presence: true
  validates :email, presence: true
  def self.find_for_authentication(conditions)
    super(conditions.merge(:creater_status => "対応可"))
  end
	def creater_status!
    	if 対応可?
         退会済!
    	else
         退会済!
    	end
  end
  def inactive_message
  退会済? super :invaild_status
  end
end

app/controllers/creaters/confirmations_controller.rb
# frozen_string_literal: true

class Creaters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/creaters/offers_controller.rb
class Creaters::OffersController < ApplicationController
	before_action :authenticate_creater!
	def index
		@q = Offer.ransack(params[:q])
		@offers = @q.result(distinct: true).page(params[:page]).per(10)
	end
	def show
		@offer = Offer.find(params[:id])
	end
  private
	def offer_params
		params.require(:offer).permit(:employer_id,:title,:content,:deadline,:delivery_date,:wage,:payment_method,:payday,:offer_status)
	end
end

app/controllers/creaters/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Creaters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/creaters/passwords_controller.rb
# frozen_string_literal: true

class Creaters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/creaters/projects_controller.rb
class Creaters::ProjectsController < ApplicationController
	before_action :authenticate_creater!
	def index
		@creater = current_creater
		@projects = Project.where(creater_id: current_creater.id).page(params[:page]).per(10)
	end
	def show
		@creater = current_creater
		@project = Project.find(params[:id])
	end
	def update
		@project = Project.find(params[:id])
		@project.update(project_params)
		flash[:success] = '更新しました'
		redirect_to creaters_project_path(@project)
	end
	private
	def project_params
		params.permit(:project_status)
	end
end

app/controllers/creaters/registrations_controller.rb
# frozen_string_literal: true

class Creaters::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :kana_name, :career, :age])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/creaters/requests_controller.rb
class Creaters::RequestsController < ApplicationController
	before_action :authenticate_creater!, only: [:new,:create,:index]
	def new
		@offer = Offer.find(params[:offer_id])
		@request = Request.new
	end
	def create
		@creater = current_creater
		@offer = Offer.find(params[:offer_id])
		@request = Request.new(request_params)
		@request.creater_id = current_creater.id
		@request.offer_id = @offer.id
		if  @request.save
			flash[:notice] = '申請が完了しました'
			redirect_to edit_creaters_offer_request_path(@offer,@request)
		else
			flash[:alert] = '申請に失敗しました'
			render :new
		end
	end
	def index
		@creater = current_creater
		@requests = @creater.requests.page(params[:page]).per(10)
	end
	def edit
		@creater = current_creater
		@request = Request.find(params[:id])
		@offer = Offer.find(params[:offer_id])
	end
	def destroy
		@request = Request.find(params[:id])
		@request.destroy
		flash[:notice] = '削除が完了しました'
		redirect_to creaters_requests_path
	end
  private
	def request_params
		params.require(:request).permit(:creater_id,:offer_id,:opinion,:request_status,:hope_salary,:production_span,:payment_method)
	end
end

app/controllers/creaters/sessions_controller.rb
# frozen_string_literal: true

class Creaters::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/creaters/unlocks_controller.rb
# frozen_string_literal: true

class Creaters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/creaters_controller.rb
class CreatersController < ApplicationController
	protect_from_forgery
	before_action :authenticate_creater!
	before_action :set_creater, only: [:show, :edit, :update, :destroy, :creater_status]
	def show
	end
	def cancel
		@creater = current_creater
	end
	def edit
		@creater = current_creater
	end
	def update
		@creater = current_creater
		url = params[:creater][:youtube_url]
    	url = url.last(11)
   		@creater.youtube_url = url
		@creater.update(creater_params)
		flash[:notice] = "更新しました"
		redirect_to creater_path(@creater)
	end
	def creater_status
		@creater.creater_status!
		redirect_to destroy_creater_session_path
	end

	private
	def creater_params
		params.require(:creater).permit(:email, :name, :kana_name,:address,:introduction,:skill,:career,:cost,:creater_status,:age)
	end
	def set_creater
		@creater = current_creater || Creater.find(params[:id])
	end
end

app/controllers/employers/creaters_controller.rb
class Employers::CreatersController < ApplicationController
	before_action :authenticate_employer!
	def index
		@q = Creater.ransack(params[:q])
		@creaters = @q.result(distinct: true).page(params[:page]).per(8)
	end
	def show
		@creater = Creater.find(params[:id])
	end
end

app/helpers/creaters/offers_helper.rb
module Creaters::OffersHelper
end

app/helpers/creaters/projects_helper.rb
module Creaters::ProjectsHelper
end

app/helpers/creaters/requests_helper.rb
module Creaters::RequestsHelper
end

app/helpers/creaters_helper.rb
module CreatersHelper
end

app/helpers/employers/creaters_helper.rb
module Employers::CreatersHelper
end

app/views/creaters/cancel.html.erb
<div class="container">
    <div class="row　header">
        <%= render 'shared/header' %>
        <%= render 'shared/flash' %>
    </div>
    <div class="cancel-box">
        <div class="row">
            <h3 class="col-xs-12 text-center cancel-text">本当に退会しますか？</h3><br><br>
            <h3 class="col-xs-12 text-center cancel-text">退会すると今後ログインができなくなります</h3>
            <h3 class="col-xs-12 text-center cancel-text">退会する場合は、「退会する」ボタンをクリックしてください</h3>
        </div>
        <div class="row cancel-button">
            <%= form_for(@creater) do |f| %>
            <div class="col-xs-3"></div>
            <%= link_to creater_path(@creater) do %>
            <p class="btn btn-primary col-xs-2">退会しない</p>
            <% end %>
            <div class="col-xs-2"></div>
            <%= link_to "退会する", creater_creater_status_path(current_creater),method: :patch, class: "btn btn-danger col-xs-2" %>
            <% end %>
        </div>
    </div>
</div>

app/views/creaters/edit.html.erb
<div class="container">
    <div class="row　header">
        <%= render 'shared/header' %>
    </div>
    <%= render 'shared/flash' %>
    <div class="row cre-edit">
        <h1 class="cre-edit-title">登録情報編集</h1>
        <div class="row cre-edit-table col-xs-12">
            <%= form_for(@creater) do |f| %>
            <div class="col-xs-6">
                <table class="table">
                    <tr>
                        <th class="col-xs-3">ユーザー名</th>
                        <td>
                            <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "cre-name",value: @creater.name %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">カナ名</th>
                        <td>
                            <%= f.text_field :kana_name, autofocus: true, autocomplete: "kana_name", class: "cre-name",value: @creater.kana_name %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">居住地</th>
                        <td>
                            <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "cre-address",value: @creater.address %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">メール</th>
                        <td>
                            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "cre-email",value: @creater.email %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">キャリア</th>
                        <td>
                            <%= f.number_field :career, autofocus: true, autocomplete: "career", class: "cre-career",value: @creater.career %>年
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">希望報酬</th>
                        <td>
                            <%= f.number_field :cost, autofocus: true, autocomplete: "cost", class: "cre-cost",value: @creater.cost %>円程度
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">年齢</th>
                        <td>
                            <%= f.number_field :age, autofocus: true, autocomplete: "age", class: "cre-age",value: @creater.age %>歳
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-3">スキル</th>
                        <td>
                            <%= f.text_area :skill, autofocus: true, autocomplete: "skill", class: "cre-intro",value: @creater.skill %>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-6">
                <table class="table">
                    <tr>
                        <th>紹介文</th>
                        <td>
                            <%= f.text_area :introduction,rows: 10, class: "cre-intro",value: @creater.introduction %>
                        </td>
                    </tr>
                    <tr>
                        <th>ポートフォリオ<br>
                            (YouTubeURL)</th>
                        <td>
                            <%= f.text_field :youtube_url,rows: 10, class: "cre-url" %>
                        </td>
                    </tr>
                </table>
                <div class="cre-edit-btn">
                    <div class="col-xs-3"></div>
                    <%= f.submit "更新する", class: "btn btn-primary col-xs-3" %>
                    <div class="col-xs-3"></div>
                    <%= link_to creater_cancel_path(current_creater) do %>
                    <p class="btn btn-danger col-xs-3">退会する</p>
                    <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container cre-profile">
    <div class="row cre-box">
        <div class="col-xs-10">
            <div class="col-xs-5">
                <table class="table">
                    <tr>
                        <th class="col-xs-2">お名前(カナ名)</th>
                    </tr>
                    <tr class="emp-cre-profile1">
                        <td class="col-xs-4">
                            <%= @creater.name %><br>
                            (<%= @creater.kana_name %>)
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-2">メールアドレス</th>
                    </tr>
                    <tr class="emp-cre-profile1">
                        <td class="col-xs-4">
                            <%= @creater.email %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-2">居住地</th>
                    </tr>
                    <tr class="emp-cre-profile1">
                        <td class="col-xs-4">
                            <%= @creater.address %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-2">キャリア</th>
                    </tr>
                    <tr class="emp-cre-profile1">
                        <td>
                            <%= @creater.career %>年
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-2">対応ステータス</th>
                    </tr>
                    <tr class="emp-cre-profile1">
                        <td>
                            <%= @creater.creater_status%>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-2">スキル</th>
                    </tr>
                    <tr class="emp-cre-profile2">
                        <td>
                            <%= simple_format(@creater.skill) %>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-7">
                <table class="table">
                    <tr>
                        <th class="col-xs-2">自己紹介</th>
                    </tr>
                    <tr class="emp-cre-intro">
                        <td>
                            <%= simple_format(@creater.introduction) %>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-xs-2">ポートフォリオ</th>
                    </tr>
                    <tr class="emp-cre-movie">
                        <td>
                            <iframe width="400" height="250" src="https://www.youtube.com/embed/<%= @creater.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/creaters/show.html.erb
<div class="container cre-show">
    <div class="row　header">
        <%= render 'shared/header' %>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="col-xs-6 cre-menu">
            	<%= link_to creaters_offers_path do %>
				<p class="cre-menu-font">案件一覧</p>
				<% end %>
				<i class="fas fa-search cre-icon"></i>
            </div>

            <div class="col-xs-6 cre-menu">
				<%= link_to creaters_requests_path do %>
				<p class="cre-menu-font">申請一覧</p>
				<% end %>
                <i class="far fa-handshake cre-icon"></i>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="col-xs-6 cre-menu">
                <%= link_to creaters_projects_path do %>
				<p class="cre-menu-font">受注案件</p>
				<% end %>
                <i class="far fa-list-alt cre-icon"></i>
            </div>
            <div class="col-xs-6 cre-menu">
                <%= link_to edit_creater_path(current_creater) do %>
				<p class="cre-menu-font">ユーザー設定</p>
				<% end %>
                <i class="fas fa-user-cog cre-icon"></i>
            </div>
        </div>
    </div>
</div>