config/routes.rb
Rails.application.routes.draw do
  devise_for :employers, controllers: {
  	sessions: 'employers/sessions',
  	passwords: 'employers/passwords',
  	registrations: 'employers/registrations'
  }

  devise_for :creaters, controllers: {
  	sessions: 'creaters/sessions',
  	passwords: 'creaters/passwords',
  	registrations: 'creaters/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get '/about', to: 'homes#about'
  root 'articles#index'

  namespace :creaters do
    resources :projects, only: [:index,:show, :edit, :update, :destroy]
    resources :offers do
      resources :requests, only: [:new, :create, :edit, :update, :destroy]
    end
    get '/requests', to: 'requests#index'
  end

  resources :creaters do
    patch :creater_status
    get '/cancel', to: 'creaters#cancel'
  end

  namespace :employers do
    resources :creaters, only: [:index, :show]
    resources :offers, only: [:index, :show, :new, :create, :edit, :update] do
      resources :requests, only: [:index, :show, :edit, :update, :destroy] do
          resources :projects, only: [:new, :create, :destroy]
      end
    end
  end

  resources :employers do
    patch :employer_status
    get '/cancel', to: 'employers#cancel'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creater.rb
class Creater < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :articles
	has_many :projects
	has_many :requests
	enum creater_status: {対応可: 0, 退会済: 1}
  validates :creater_status, inclusion: { in: Creater.creater_statuses.keys }
  validates :name, presence: true
  validates :kana_name, presence: true
  validates :career, presence: true
  validates :email, presence: true
  def self.find_for_authentication(conditions)
    super(conditions.merge(:creater_status => "対応可"))
  end
	def creater_status!
    	if 対応可?
         退会済!
    	else
         退会済!
    	end
  end
  def inactive_message
  退会済? super :invaild_status
  end
end

app/models/employer.rb
class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
		   :recoverable, :rememberable, :validatable
	has_many :offers
    enum employer_status: {有効: 0, 無効: 1 }
    validates :employer_name, presence: true
    validates :employer_status, inclusion: { in: Employer.employer_statuses.keys }
    def self.find_for_authentication(conditions)
    super(conditions.merge(:employer_status => "有効"))
    end
    def employer_status!
    	if 有効?
    		無効!
    	else
    		無効!
    	end
    end
    def inactive_message
    無効? super :invaild_status
    end
end

app/models/offer.rb
class Offer < ApplicationRecord
	has_many :requests
	has_many :projects
	enum offer_status: {募集中: 0, 募集終了: 1}
	validates :title, presence: true
	validates :content, presence: true
	validates :deadline, presence: true
	validates :delivery_date, presence: true
	validates :wage, presence: true
	validates :payment_method, presence: true
	validates :payday, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :request
	belongs_to :offer
	accepts_nested_attributes_for :request
	enum offer_status: {製作中: 0,製作完了: 1}
end

app/models/request.rb
class Request < ApplicationRecord
	has_one :project
	enum request_status: {申請中:0, 契約済:1}
	belongs_to :offer
	belongs_to :creater
	validates :opinion, presence: true
	validates :hope_salary, presence: true
	validates :production_span, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resources)
		flash[:notice] = "ログインしました"
		if creater_signed_in?
			creater_path(current_creater)
		else
			employer_path(current_employer)
		end
	end

	def after_sign_out_path_for(resources)
		flash[:notice] = "ログアウトしました"
		root_path
	end
end

app/controllers/creaters_controller.rb
class CreatersController < ApplicationController
	protect_from_forgery
	before_action :authenticate_creater!
	before_action :set_creater, only: [:show, :edit, :update, :destroy, :creater_status]
	def show
	end
	def cancel
		@creater = current_creater
	end
	def edit
		@creater = current_creater
	end
	def update
		@creater = current_creater
		url = params[:creater][:youtube_url]
    	url = url.last(11)
   		@creater.youtube_url = url
		@creater.update(creater_params)
		flash[:notice] = "更新しました"
		redirect_to creater_path(@creater)
	end
	def creater_status
		@creater.creater_status!
		redirect_to destroy_creater_session_path
	end

	private
	def creater_params
		params.require(:creater).permit(:email, :name, :kana_name,:address,:introduction,:skill,:career,:cost,:creater_status,:age)
	end
	def set_creater
		@creater = current_creater || Creater.find(params[:id])
	end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
	protect_from_forgery
	before_action :authenticate_employer!
	before_action :set_employer, only: [:show, :edit, :update, :destroy, :employer_status]
	def show
	end
	def edit
		@employer = current_employer
	end
	def update
		@employer = current_employer
		@employer.update(employer_params)
		flash[:notice] = "更新しました"
		redirect_to employer_path
	end
	def cancel
		@employer = current_employer
	end
	def employer_status
		@employer.employer_status!
		redirect_to destroy_employer_session_path
	end

	private
	def employer_params
		params.require(:employer).permit(:employer_name, :summary, :employer_status)
	end
	def set_employer
		@employer = current_employer || Employer.find(params[:id])
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creaters/offers_helper.rb
module Creaters::OffersHelper
end

app/helpers/creaters/projects_helper.rb
module Creaters::ProjectsHelper
end

app/helpers/creaters/requests_helper.rb
module Creaters::RequestsHelper
end

app/helpers/creaters_helper.rb
module CreatersHelper
end

app/helpers/employers/creaters_helper.rb
module Employers::CreatersHelper
end

app/helpers/employers/offers_helper.rb
module Employers::OffersHelper
end

app/helpers/employers/projects_helper.rb
module Employers::ProjectsHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/shared/_flash.html.erb
<div class="flash">
    <% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
        <%= value %>
    </p>
    <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img alt="Brand" src="<%= asset_path "logo1.png" %>" style="height: 30px; border-radius: 5px; width: 100px;">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <!-- クリエイターメニュー -->
                <% if creater_signed_in? %>
                <li>
                    <%= link_to creater_path(current_creater) do %>
                    マイページ
                    <% end %>
                </li>
                <li>
                    <%= link_to creaters_offers_path do %>
                    オファーを探す
                    <% end %>
                </li>
                <li>
                    <%= link_to creaters_requests_path do %>
                    リクエスト一覧
                    <% end %>
                </li>
                <li>
                    <%= link_to creaters_projects_path do %>
                    受注内容一覧
                    <% end %>
                </li>
                <li>
                    <%= link_to destroy_creater_session_path do %>
                    ログアウト
                    <% end %>
                </li>
                <li>
                    <%= link_to about_path do %>
                    使い方
                    <% end %>
                </li>
                <!-- エンプロイヤーメニュー -->
                <% elsif employer_signed_in? %>
                <li>
                    <%= link_to employer_path(current_employer) do %>
                    マイページ
                    <% end %>
                </li>
                <li>
                    <%= link_to new_employers_offer_path do %>
                    仕事を依頼する
                    <% end %>
                </li>
                <li>
                    <%= link_to employers_offers_path do %>
                    マイオファー
                    <% end %>
                </li>
                <li>
                    <%= link_to employers_creaters_path do %>
                    クリエイターを探す
                    <% end %>
                </li>
                <li>
                    <%= link_to destroy_employer_session_path do %>
                    ログアウト
                    <% end %>
                </li>
                <li>
                    <%= link_to about_path do %>
                    使い方
                    <% end %>
                </li>
                <!-- ログイン前 -->
                <% else %>
                <li>
                    <%= link_to new_creater_registration_path do %>
                    <p class="nav-menu">クリエイターの方はこちら</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to  new_employer_registration_path do %>
                    <p class="nav-menu">Youtuberの方はこちら</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to about_path do %>
                    <p class="nav-menu">使い方</p>
                    <% end %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>