config/routes.rb
Rails.application.routes.draw do
  devise_for :employers, controllers: {
  	sessions: 'employers/sessions',
  	passwords: 'employers/passwords',
  	registrations: 'employers/registrations'
  }

  devise_for :creaters, controllers: {
  	sessions: 'creaters/sessions',
  	passwords: 'creaters/passwords',
  	registrations: 'creaters/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get '/about', to: 'homes#about'
  root 'articles#index'

  namespace :creaters do
    resources :projects, only: [:index,:show, :edit, :update, :destroy]
    resources :offers do
      resources :requests, only: [:new, :create, :edit, :update, :destroy]
    end
    get '/requests', to: 'requests#index'
  end

  resources :creaters do
    patch :creater_status
    get '/cancel', to: 'creaters#cancel'
  end

  namespace :employers do
    resources :creaters, only: [:index, :show]
    resources :offers, only: [:index, :show, :new, :create, :edit, :update] do
      resources :requests, only: [:index, :show, :edit, :update, :destroy] do
          resources :projects, only: [:new, :create, :destroy]
      end
    end
  end

  resources :employers do
    patch :employer_status
    get '/cancel', to: 'employers#cancel'
  end

end

app/models/employer.rb
class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
		   :recoverable, :rememberable, :validatable
	has_many :offers
    enum employer_status: {有効: 0, 無効: 1 }
    validates :employer_name, presence: true
    validates :employer_status, inclusion: { in: Employer.employer_statuses.keys }
    def self.find_for_authentication(conditions)
    super(conditions.merge(:employer_status => "有効"))
    end
    def employer_status!
    	if 有効?
    		無効!
    	else
    		無効!
    	end
    end
    def inactive_message
    無効? super :invaild_status
    end
end

app/controllers/employers/confirmations_controller.rb
# frozen_string_literal: true

class Employers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employers/creaters_controller.rb
class Employers::CreatersController < ApplicationController
	before_action :authenticate_employer!
	def index
		@q = Creater.ransack(params[:q])
		@creaters = @q.result(distinct: true).page(params[:page]).per(8)
	end
	def show
		@creater = Creater.find(params[:id])
	end
end

app/controllers/employers/offers_controller.rb
class Employers::OffersController < ApplicationController
	before_action :authenticate_employer!
	def index
		@employer = current_employer
		@offers = @employer.offers.page(params[:page]).per(10)
	end
	def show
		@employer = current_employer
		@offer = Offer.find(params[:id])
	end
	def new
		@employer = current_employer
		@offer = Offer.new
	end
	def create
		@employer = current_employer
		@offer = Offer.new(offer_params)
		@offer.employer_id = current_employer.id
		if  @offer.save
			flash[:notice] = '発注が完了しました'
			redirect_to employers_offer_path(@offer)
		else
			flash[:alert] = '作成に失敗しました'
			render :new
		end
	end
	def edit
		@offer = Offer.find(params[:id])
	end
	def update
		@offer = Offer.find(params[:id])
		@offer.update(offer_params)
		flash[:success] = '更新しました'
		redirect_to employers_offer_path(@offer)
	end
	def destroy
		@offer = Offer.find(params[:id])
		@offer.destroy
		flash[:success] = '削除しました'
		redirect_to employers_offers_path
	end
	private
	def offer_params
		params.require(:offer).permit(:employer_id,:title,:content,:deadline,:delivery_date,:wage,:payment_method,:payday,:offer_status)
	end
end

app/controllers/employers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employers/passwords_controller.rb
# frozen_string_literal: true

class Employers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employers/projects_controller.rb
class Employers::ProjectsController < ApplicationController
	before_action :authenticate_employer!
	def new
		@project = Project.new
	end
	def create
		@employer = current_employer
		@project = Project.new(project_params)
		@offer = Offer.find(params[:offer_id])
		@request = Request.find(params[:request_id])
		@project.creater_id = @request.creater_id
		@project.offer_id = @request.offer_id
		@project.request_id = @request.id
		@project.demand = @offer.content
		@project.reward = @offer.wage
		@project.time_limit = @offer.delivery_date
		if  @project.save
			if @request.request_status == "申請中"
				@request.update(request_status: "契約済")
			end
			flash[:notice] = '発注が完了しました'
			redirect_to employers_offer_requests_path(@offer)
		else
			flash[:alert] = '発注に失敗しました'
			render :show
		end
	end
	private
	def project_params
		params.permit(:creater_id,:request_id,:offer_id,:reward,:demand,:project_status,:time_limit, request_attributes: [:id, :request_status])
	end
end

app/controllers/employers/registrations_controller.rb
# frozen_string_literal: true

class Employers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:employer_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers/requests_controller.rb
class Employers::RequestsController < ApplicationController
	before_action :authenticate_employer!
	def index
		@offer = Offer.find(params[:offer_id])
		@requests = @offer.requests.page(params[:page]).per(10)
	end
	def show
		@employer = current_employer
		@request = Request.find(params[:id])
		@offer = Offer.find(params[:offer_id])
		@creater = Creater.find(@request.creater_id)
	end
	def destroy
		@request = Request.find(params[:id])
		@request.destroy
		@offer = Offer.find(params[:offer_id])
		flash[:notice] = '削除が完了しました'
		redirect_to employers_offer_requests_path(@offer)
	end

	private
	def request_params
	params.require(:request).permit(:creater_id, :offer_id, :opinion, :request_status, :hope_salary, :production_span)
	end
end

app/controllers/employers/sessions_controller.rb
# frozen_string_literal: true

class Employers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employers/unlocks_controller.rb
# frozen_string_literal: true

class Employers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
	protect_from_forgery
	before_action :authenticate_employer!
	before_action :set_employer, only: [:show, :edit, :update, :destroy, :employer_status]
	def show
	end
	def edit
		@employer = current_employer
	end
	def update
		@employer = current_employer
		@employer.update(employer_params)
		flash[:notice] = "更新しました"
		redirect_to employer_path
	end
	def cancel
		@employer = current_employer
	end
	def employer_status
		@employer.employer_status!
		redirect_to destroy_employer_session_path
	end

	private
	def employer_params
		params.require(:employer).permit(:employer_name, :summary, :employer_status)
	end
	def set_employer
		@employer = current_employer || Employer.find(params[:id])
	end
end

app/helpers/employers/creaters_helper.rb
module Employers::CreatersHelper
end

app/helpers/employers/offers_helper.rb
module Employers::OffersHelper
end

app/helpers/employers/projects_helper.rb
module Employers::ProjectsHelper
end

app/helpers/employers/requests_helper.rb
module Employers::RequestsHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/cancel.html.erb
<div class="container" style="padding: 50px;">
    <div class="row　header">
        <%= render 'shared/header' %>
        <%= render 'shared/flash' %>
    </div>
    <div class="row">
        <h3 class="col-xs-12 text-center cancel-font">退会すると今後ログインが出来なくなります<br>
        本当に退会しますか？
        </h3>
    </div>
    <div class="row cancel-button">
        <%= form_for(@employer) do |f| %>
        <%= link_to employer_path(@employer) do %>
        <p class="btn btn-lg btn-primary col-xs-2">退会しない</p>
        <% end %>
        <div class="col-xs-8"></div>
        <%= link_to "退会する", employer_employer_status_path(current_employer),method: :patch, class: "btn btn-lg btn-danger col-xs-2" %>
        <% end %>
    </div>
</div>

app/views/employers/edit.html.erb
<div class="container">
    <div class="row　header">
        <%= render 'shared/header' %>
        <%= render 'shared/flash' %>
    </div>
    <div class="row">
        <h1>登録情報編集</h1>
        <% if @employer.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= @employer.errors.count %>件のエラーが発生しました。</h2>
            <ul>
                <% @employer.errors.full_messages.each do |message| %>
                <li>error
                    <%= message %>
                </li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <div class="row mypage-table col-xs-12">
            <%= form_for(@employer) do |f| %>
            <table class="table">
                <tr>
                    <th class="col-xs-2">クライアント名</th>
                    <td class="col-xs-12">
                        <%= f.text_field :employer_name, autofocus: true, autocomplete: "employer_name", class: "emp-name",value: @employer.employer_name %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-2">メール</th>
                    <td>
                        <%= f.text_field :email, autofocus: true, autocomplete: "email", class: "emp-name",value: @employer.email %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-2">紹介文</th>
                    <td class="col-xs-12">
                        <%= f.text_area :summary,rows: 10, class: "emp-summary",value: @employer.summary %>
                    </td>
                </tr>
            </table>
        </div>
        <div class="row col-xs-12">
            <%= f.submit "保存する", class: "btn btn-primary col-xs-1" %>
            <% end %>
            <div class="col-xs-10"></div>
            <%= link_to employer_cancel_path(current_employer) do %>
            <p class="btn btn-danger col-xs-1">退会する</p>
            <% end %>
        </div>
    </div>
</div>
</div>

app/views/employers/show.html.erb
<div class="container">
    <div class="row　header">
        <%= render 'shared/header' %>
        <%= render 'shared/flash' %>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="col-xs-6 emp-menu">
            	<%= link_to employers_creaters_path do %>
				<p class="emp-menu-font">クリエイターを探す</p>
				<% end %>
				<i class="far fa-address-card emp-icon"></i>
            </div>

            <div class="col-xs-6 emp-menu">
				<%= link_to new_employers_offer_path do %>
				<p class="emp-menu-font">仕事を提案</p>
				<% end %>
                <i class="fas fa-briefcase emp-icon"></i>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="col-xs-6 emp-menu">
                <%= link_to employers_offers_path do %>
				<p class="emp-menu-font">マイオファー</p>
				<% end %>
                <i class="far fa-list-alt emp-icon"></i>
            </div>
            <div class="col-xs-6 emp-menu">
                <%= link_to edit_employer_path(current_employer) do %>
				<p class="emp-menu-font">クライアント設定</p>
				<% end %>
                <i class="fas fa-user-cog emp-icon"></i>
            </div>
        </div>
    </div>
</div>